# -*- coding: utf-8 -*-
"""YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    <ORIGINAL_COLAB_NOTEBOOK>
"""

#라벨링된 데이터를 roboflow에서 다운로드받고 unzip을 하는 과정
#curl -L "<YOUR_ROBOFLOW_DOWNLOAD_URL>" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip
#해당 경로에서 데이터를 다운로드 하고, 하단 DATA_YAML 파트를 수정해야함.


from ultralytics import YOLO

DATA_YAML = "/content/data.yaml"

# 1) 모델 로드
model = YOLO("yolov8n.pt")   # 또는 yolo11n.pt 등 사용중인 가중치

# 2) 학습 (train + val 자동 사용)
train_results = model.train(
    data=DATA_YAML,
    epochs=30,
    imgsz=640,
    batch=16,
    name="exp_train"
)

# 3) 최종 테스트 평가 (test split)
test_metrics = model.val(
    data=DATA_YAML,
    split="test"
)

print("TEST metrics:", test_metrics)

from ultralytics import YOLO

DATA_YAML = "/content/data.yaml"

# 1) 모델 로드
model = YOLO("yolo11n.pt")   # 또는 yolo11n.pt 등 사용중인 가중치

# 2) 학습 (train + val 자동 사용)
train_results = model.train(
    data=DATA_YAML,
    epochs=30,
    imgsz=640,
    batch=16,
    name="exp_train"
)

# 3) 최종 테스트 평가 (test split)
test_metrics = model.val(
    data=DATA_YAML,
    split="test"
)

print("TEST metrics:", test_metrics)

from ultralytics import YOLO

DATA_YAML = "/content/data.yaml"

# 1) 모델 로드
model = YOLO("yolo26n.pt")   # 또는 yolo11n.pt 등 사용중인 가중치

# 2) 학습 (train + val 자동 사용)
train_results = model.train(
    data=DATA_YAML,
    epochs=30,
    imgsz=640,
    batch=16,
    name="exp_train"
)

# 3) 최종 테스트 평가 (test split)
test_metrics = model.val(
    data=DATA_YAML,
    split="test"
)

print("TEST metrics:", test_metrics)
